// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oljeyylnbfoudlssmmgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9samV5eWxuYmZvdWRsc3NtbWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzk5NzIsImV4cCI6MjA2NTcxNTk3Mn0.BjpA9uxGeMxTMQcGIPP0VIJhKXLqrv2Z-041IwEdSSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'aimploy-auth-token',
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    debug: process.env.NODE_ENV === 'development',
    onAuthStateChange: (event, session) => {
      // Handle auth state changes globally
      if (event === 'SIGNED_OUT') {
        // Clear any additional storage on sign out
        if (typeof window !== 'undefined') {
          localStorage.removeItem('login_time');
          sessionStorage.clear();
        }
      }
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'aimploy-hr-recruitment'
    }
  }
});

// Add error handling for network issues
if (typeof window !== 'undefined') {
  // Handle offline/online events
  window.addEventListener('online', () => {
    console.log('Network connection restored');
  });
  
  window.addEventListener('offline', () => {
    console.log('Network connection lost');
  });
}